# Generated by Django 4.1.5 on 2023-01-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_userprofile_es_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado_hasta_month', models.PositiveSmallIntegerField()),
                ('pagado_hasta_year', models.PositiveSmallIntegerField()),
                ('activo_hasta_month', models.PositiveSmallIntegerField()),
                ('activo_hasta_year', models.PositiveSmallIntegerField()),
                ('es_activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='userprofile.userprofile')),
            ],
        ),
    ]
