# Generated by Django 3.2.16 on 2023-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='activo_hasta_month',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='activo_hasta_year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='pagado_hasta_month',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='pagado_hasta_year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
