# Generated by Django 4.1.5 on 2023-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
