# Generated by Django 3.2.16 on 2023-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activo_hasta_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activo_hasta_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagado_hasta_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagado_hasta_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
